version: "3.9"

networks: 
  doodlspace:
    external: true

services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks: 
      - doodlspace
  
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    labels:
      - traefik.enable=false
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    networks: 
      - doodlspace
    
volumes:
  mongo-data:
