version: "3.9"

networks:
  web:
    external: true
  internal:
    external: false
  doodlspace:
    external: true

services:
  app:
    build:
      context: .
    labels:
      - traefik.http.routers.doodlspace-backend.rule=Host(`test-api.doodlspace.com`)
      - traefik.http.routers.doodlspace-backend.tls=true
      - traefik.http.routers.doodlspace-backend.tls.certresolver=lets-encrypt
      - traefik.port=3000
    depends_on:
      - db
    networks:
      - web
      - internal
  
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    labels:
      - traefik.enable=false
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    networks:
      - internal
      - doodlspace
    
volumes:
  mongo-data:
